config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'
  get '/search' => 'photos#search', :as => 'search_photo'
  resources :photos do
    resources :comments
  end

  resources :categories do
    resources :photos
    resources :comments
  end
  # For details on the DSL available within
  resources :searches
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :cover, presence: true
  has_many :photos, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :cover
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :image, presence: true
  belongs_to :category, counter_cache: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET Categories
  def index
    @categories = Category.all
  end

  # GET/Category/:id/show
  def show
    @category = Category.find(params[:id])
    @photos = @category.photos
  end

  # GET New category
  def new
    @category = Category.new
  end

  # POST /Category
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  # GET/Category/:id/edit
  def edit
    @category = Category.find(params[:id])
  end

  # PATCH/Category/:id
  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  # DELETE/Category/:id
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :cover) # cover?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if params[:category_id].blank?
      condition_photos
    else
      condition_categories
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    if @comment.commentable_type == 'category'
      redirect_to photo_path(@comment.commentable_id)
    else
      redirect_to category_path(@comment.commentable_id)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def condition_categories
    @category = Category.find(params[:category_id])
    @comment = @category.comments.create(comment_params)
    redirect_to category_path(@comment.commentable_id)
  end

  def condition_photos
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.create(comment_params)
    redirect_to photo_path(params[:photo_id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @categories = Category.all
    @photo = Photo.new(category: @category)
  end

  def edit
    @photo = Photo.find(params[:id])
    @categories = Category.all
  end

  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      redirect_to @photo
    else
      @category = Category.find(@photo[:category_id])
      @categories = Category.all
      render :new
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to category_photo_path(@photo)
    else
      @category = Category.find(@photo[:category_id])
      @categories = Category.all
      render :edit
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to category_path(@photo.category)
  end

  def search
    @results = if params[:search].blank?
                 Photo.where('lower(title) LIKE :search', search: ' ')
               else
                 Photo.where('lower(title) LIKE :search', search: "%#{params[:search]}%")
               end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :category_id, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<% if @category.errors.size.positive? %>
  <div>
    <ul>
      <h2>Something went wrong:</h2>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @category  do |form| %>
  <div>
      <%= form.label :name, class: 'form-label'%>
      <%= form.text_field :name, class: 'form-text-field'%>
  </div>

  <div>
      <%= form.label :description, class: 'form-label'%>
      <%= form.text_area :description ,class: 'form-text-area'%>
  </div>

  <div>
      <%= form.label :cover, class: 'form-label'%>
      <% if @category.cover.attached?%>
        <%= image_tag @category.cover %>
      <% end %>
      <%= form.file_field :cover%>
  </div>

  <%= form.submit%>
<% end %>
<button class="button-back"><%=link_to 'Back' , categories_path %></button>

app/views/categories/index.html.erb

<section class = "card_photo">
  <div class="container">
    <div>
    <h1>Categories</h1>
    <button class = "button_new_category"><%= link_to 'New Category', new_category_path %></button>
    </div>
    <div class="categories-list">
      <% @categories.each do |category| %>
      <div class = "cards">
        <a href="<%= category_path(category)%>">
          <%= image_tag category.cover %>
        </a>
        <div class = "ajuste_ctg">
        <h3><%= category.name%></h3>
        <span><%= category.photos_count ? category.photos_count : 0%> photos</span>
        <p><%= category.description%></p>
        </div>
        <div class = "button_edit_and_delete">
        <div> 
          <%= link_to image_tag('edit.png', alt: "Button edit"), edit_category_path(category) %>
        </div>
        <div>
          <%= link_to image_tag('delete.png', alt: "Delete"), category_path(category), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<h1>New Category</h1>

<% if @category.errors.size.positive? %>
  <div>
    <ul>
      <h2>Something went wrong:</h2>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @category  do |form| %>
  <div>
      <%= form.label :name, class: 'form-label'%>
      <%= form.text_field :name, class: 'form-text-field',  autofocus: true, placeholder: 'Technology'%>
  </div>

  <div>
      <%= form.label :description, class: 'form-label'%>
       <%= form.text_area :description,class: 'form-text-area', autofocus: true,
       placeholder: 'Exploring our complicated relationship with technology...'%>
  </div>

  <div>
      <%= form.label :cover, class: 'form-label'%>
      <%= form.file_field :cover%>
  </div>

  <%= form.submit%>
<% end %>
<button class="button-back"><%=link_to 'Back' , categories_path %></button>

app/views/categories/show.html.erb
<div class = "card_photo">
<h1><%= @category.name%></h1>
<p><%= @category.description%></p>
<button class="button_new_category"><%= link_to 'New Photo', new_category_photo_path(category_id: @category.id) %></button>
<div>
  <% @photos.each do |photo| %>
    <div class="photo">
      <a href="<%= photo_path(photo)%>">
        <%= image_tag photo.image if photo.image.attached? %>
      </a>
      <div>
        <div>
          <span class="h4"><%= photo.title %></span>
        </div>
        <div class="footer">
          <div>
            <span><%= photo.comments.count %> <%= photo.comments.count > 1 ? "comments" : "comment" %></span>
          </div>
          <div>
            <%= link_to image_tag('edit.png', alt: "Button edit"), edit_photo_path(photo)%>
            <%= link_to image_tag('delete.png', alt: "Delete"), method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>
<div class = "order_comments">
  <%= render @category.comments %>
  <p class = "commenth2">Comments</p>
  <%= render 'comments/forms' %>
</div>
</div>

app/views/comments/_comment.html.erb
<div class = "comments_style">
  <p>
    <%= comment.text %>
  </p>
  <div class = "time_and_delete">
  <span> send
    <%= time_ago_in_words(comment.updated_at) unless comment.created_at.blank? %> ago
  </span>
  <div>
    <%= link_to [comment.commentable, comment], method: :delete, data: { confirm: "Are you sure?" } do %>
    <%= image_tag 'delete.png', width: 28, height: 28 %>
    <% end %>
  </div>
</div>
</div>

app/views/comments/_forms.html.erb
<%= form_for([@category,@category.comments.build]) do |f| %>
    <%= f.text_area :text, class: 'form-control', autofocus: true, placeholder: 'Some respectul comment here.'%>
    <%= f.submit class: 'button_comment', value: 'COMMENT' %>
<% end %>

app/views/comments/_formsp.html.erb
<%= form_for([@photo,@photo.comments.build]) do |f| %>
  <p>
    <%= f.text_area :text, class: 'form-control', autofocus: true, placeholder: 'Some respectul comment here.'%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><div><%= link_to image_tag('somesplash.png', alt: "Somesplash"), root_path %></div>
    <div><button class = "button_search"> <%= link_to "SEARCH", search_photo_path%> </button></div></header>
    <%= yield %>
    <footer>
      <h3>Build with ♥ by</h3>
      <span>Ana María - </span>
      <span> Aldo Canales -</span>
      <span> Christian Martos -</span>
      <span> Giancarlo Palomino</span>
    </footer>
  </body>
</html>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<% if @photo.errors.size.positive? %>
  <div>
    <ul>
      <h2 class="errors-title">Something went wrong:</h2>
      <% @photo.errors.full_messages.each do |message| %>
        <li class="errors-list"><%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @photo do |form| %>

  <div>
        <%= form.label :title, class: 'form-label'%>
        <%=form.text_field :title, class: 'form-text-field'%>
  </div>
  <div>
        <%= form.label :description, class: 'form-label'%>
        <%=form.text_area :description,class: 'form-text-area'%>
  </div>
 <div>
        <%= form.label :category_id, class: 'form-label'%>
        <%=form.collection_select :category_id, @categories, :id, :name,class: 'form-collection'%>
  </div>
  <div>
        <%= form.label :image,class: 'form-label'%>
    <div>
      <% if @photo.image.attached?%>
        <%=image_tag @photo.image%>
      <%end%>
    </div>
    <div>
      <%= form.file_field :image%>
    </div>
    </div>
    <%=form.submit%>
<%end%>

<button class="button-back"><%=link_to 'Back' , category_path(@photo.category_id)%></button>

app/views/photos/new.html.erb
<h1>New Photo</h1>   
 
<div>
<% if @photo.errors.size.positive? %>
  <div>
    <ul>
      <h2>Something went wrong:</h2>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>
</div>


<%= form_with model: @photo do |form| %>
  

  <div>
        <%= form.label :title, class: 'form-label'%>
        <%=form.text_field :title, class: 'form-text-field', autofocus: true, placeholder: 'Big mountain'%>
  </div>
  <div>
        <%= form.label :description, class: 'form-label'%>
        <%=form.text_area :description,class: 'form-text-area', autofocus: true, placeholder: 'Photo taken on ...'%>
  </div>
  <div>
        <%= form.label :category_id, class: 'form-label'%>
        <%=form.collection_select :category_id, @categories, :id, :name,class: 'form-collection'%>
  </div>
  <div>
        <%= form.label :image,class: 'form-label'%>
      <%= form.file_field :image%>
  </div>
  <%=form.submit%>
<%end%>

<button class="button-back"><%=link_to 'Back' , category_path(@photo.category_id)%></button>

app/views/photos/search.html.erb
<%= form_tag(search_photo_path, :method => "get", class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
    <%= button_tag "Search", :class => 'btn',:title => nil%>  
    </div>  
  </div>  
<% end %>
<div class = "card_photo">
<h3>Search</h3>  
  <% if !@results.nil? %>
    <% @results.each do |result| %>  
      <%= result.title %><br>
       <%= image_tag result.image %> 
    <% end %>
  <% end %>
</div>

app/views/photos/show.html.erb
<div class = "card_photo">
<h1><%= @photo.title%></h1>
<p><%= @photo.description%></p>
<p>Updated at <%= "August" if @photo.updated_at.month == 8 %> <%= @photo.updated_at.day%>,<%= @photo.updated_at.year%></p>
<%= image_tag @photo.image if @photo.image.attached? %>
</div>

<div class = "order_comments">
  <%= render @photo.comments %>
  <p class = "commenth2">Comments</p>
  <%= render 'comments/formsp' %>
</div>